version: '3.7'

services:
  api-frontend:
    build: .
    volumes:
        - '.:/usr/src/app'
        - '/usr/src/app/node_modules'
    ports:
        - '0.0.0.0:80:3000'
    environment:
        - NODE_ENV=development
